### PR TITLE
Do not use paged searching when limit is 1

### LINKED ISSUE #172: Loading schema with JNDI paged searching throws UnavailableCriticalExtension on OpenDJ
```
Loading test environment (Rails 4.2.11.1)
irb: warn: can't alias context from irb_context.
jruby-9.2.11.0 :001 > Person.schema
Attempting to reconnect
  LDAP: connect (1.0ms) {:uri=>"ldap://localhost:13891", :with_start_tls=>false}
  LDAP: bind (117.7ms) {:dn=>"<REDACTED>"}
Bound to ldap://localhost:13891 by simple as <REDACTED>
  LDAP: search (82.0ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["subschemaSubentry"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (5.7ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["supportedControl"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (44.5ms) {:base=>"cn=schema", :scope=>:base, :filter=>"(objectClass=subschema)", :attributes=>["objectClasses", "attributeTypes", "matchingRules", "matchingRuleUse", "dITStructureRules", "dITContentRules", "nameForms", "ldapSyntaxes"], :limit=>1, :use_paged_results=>true, :page_size=>500}
Traceback (most recent call last):
       16: from org/jruby/ext/timeout/Timeout.java:76:in `timeout'
       15: from org/jruby/ext/timeout/Timeout.java:90:in `timeout'
       14: from org/jruby/ext/timeout/Timeout.java:97:in `timeout'
       13: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:308:in `block in operation'
       12: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:150:in `block in schema'
       11: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:49:in `search'
       10: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:197:in `search'
        9: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:307:in `operation'
        8: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:354:in `with_timeout'
        7: from org/jruby/ext/timeout/Timeout.java:76:in `timeout'
        6: from org/jruby/ext/timeout/Timeout.java:90:in `timeout'
        5: from org/jruby/ext/timeout/Timeout.java:97:in `timeout'
        4: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:308:in `block in operation'
        3: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:198:in `block in search'
        2: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:52:in `block in search'
        1: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:103:in `execute'
ActiveLdap::LdapError::UnavailableCriticalExtension (The search request cannot be processed because it contains a critical control with OID 1.2.840.113556.1.4.319 that is not supported by the Directory Server for this type of operation)
```

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
Fixes #172

```
Loading test environment (Rails 4.2.11.1)
irb: warn: can't alias context from irb_context.
jruby-9.2.11.0 :001 > Person.all '(uid=*)'
Attempting to reconnect
  LDAP: connect (1.0ms) {:uri=>"ldap://localhost:13891", :with_start_tls=>false}
  LDAP: bind (54.8ms) {:dn=>"<REDACTED>"}
Bound to ldap://localhost:13891 by simple as <REDACTED>
  LDAP: search (12.5ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["supportedControl"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (87.9ms) {:base=>"ou=people,dc=weill,dc=cornell,dc=edu", :scope=>:one, :filter=>"(&(uid=*)(&(objectClass=inetOrgPerson)(objectClass=weillCornellEduPerson)))", :attributes=>["*", "isMemberOf", "createTimestamp", "modifyTimestamp", "creatorsName", "modifiersName", "objectClass"], :limit=>nil, :use_paged_results=>true, :page_size=>500}
  LDAP: search (3.1ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["subschemaSubentry"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (63.3ms) {:base=>"cn=schema", :scope=>:base, :filter=>"(objectClass=subschema)", :attributes=>["objectClasses", "attributeTypes", "matchingRules", "matchingRuleUse", "dITStructureRules", "dITContentRules", "nameForms", "ldapSyntaxes"], :limit=>1, :use_paged_results=>false, :page_size=>500}
[
    [ 0] #<Person objectClass:<top, eduPerson, inetOrgPerson, ...
```

### CODE REVIEW

File: lib/active_ldap/adapter/base.rb [hunk 1]
```diff
@@ -181,7 +181,7 @@ def search(options={})
         limit = nil if limit <= 0
         use_paged_results = options[:use_paged_results]
         if use_paged_results or use_paged_results.nil?
-          use_paged_results = supported_control.paged_results?
+          use_paged_results = limit.to_i != 1 && supported_control.paged_results?
```
Comment (kou) [inline lib/active_ldap/adapter/base.rb:184]: We don't need `.to_i` here.

Comment (HarlemSquirrel) [reply lib/active_ldap/adapter/base.rb:184]:
```suggestion
          use_paged_results = limit != 1 && supported_control.paged_results?
```

**Comment by kou** [comment]
Thanks!

**Comment by HarlemSquirrel** [comment]
@kou Do you have a moment for a patch release now that includes this fix? Thanks!

**Comment by kou** [comment]
Done!
